# Generated by Django 3.1.4 on 2021-06-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=20)),
                ('stud_name', models.CharField(max_length=64)),
                ('is_cr', models.BooleanField(default=False)),
            ],
        ),
    ]
