# Generated by Django 3.1.4 on 2021-06-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
