# Generated by Django 3.1.4 on 2021-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210605_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
